### ISSUE TITLE
[feat] 연락처 관리 앱 STEP1

### ISSUE THREAD

**Issue by MyNB1** [MyNB1/ios-contact-manager-ui#1]
## 📱 Feature Issue
- 연락처 목록 화면을 구현합니다

## 📝 To-do
- [x] 연락처 데이터모델 구성
- [x] 연락처 뷰 컨트롤러 생성
- [x] 테이블 뷰 레이아웃 구성
- [x] subtitle style 테이블뷰 셀 구성
- [x] 테이블 뷰에 셀 삽입
