### ISSUE TITLE
[feat] 연락처 관리 앱 STEP2

### ISSUE THREAD

**Issue by jane1choi** [MyNB1/ios-contact-manager-ui#3]
## 📱 Feature Issue
- 연락처 추가 기능을 구현합니다.

## 📝 To-do
- [x] 상단 네비바 추가
- [x] 화면전환(modal 방식)
- [x] 연락처 추가 뷰 화면 UI 구성
    - [x] #5
    - [x] 취소버튼 터치 -> alert 띄우기
    - [x] 저장버튼 터치 -> 입력한 정보 형식 확인 (형식에 맞지 않다면 alert 띄우기)
        - [x] 이름: 띄어쓰기 x
        - [x] 나이: 숫자 세자리 수 이하
        - [x] 연락처: - 두개, 숫자 9자리 이상
